steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'chatbot'
    args:
      - 'buildx'
      - 'build'
      - '--platform=linux/amd64'
      - '-t'
      - 'us-central1-docker.pkg.dev/project-d533213a-0f7d-4f94-94e/roworks-repo/chatbot:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/project-d533213a-0f7d-4f94-94e/roworks-repo/chatbot:latest'
      - '--push'
      - '.'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'roworks-chatbot'
      - '--image=us-central1-docker.pkg.dev/project-d533213a-0f7d-4f94-94e/roworks-repo/chatbot:$COMMIT_SHA'
      - '--region=us-central1'
      - '--project=project-d533213a-0f7d-4f94-94e'

images:
  - 'us-central1-docker.pkg.dev/project-d533213a-0f7d-4f94-94e/roworks-repo/chatbot:latest'

options:
  logging: CLOUD_LOGGING_ONLY
